apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Global options
namespace: default
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "Kubernetes"
  app.kubernetes.io/created-by: kustomizer
  endpointslice.kubernetes.io/managed-by: controller
  pod-security.kubernetes.io/audit: baseline
  pod-security.kubernetes.io/warn-version: latest
#namespace: monitoring

# Generate a ConfigMap for each dashboard
configMapGenerator:

#################################################
# Views Dashboards
#################################################

- name: dashboards-k8s-pv-global
  files: [ dashboards/kubernetes-persistent-volumes.json ]
#
#- name: dashboards-k8s-views-namespaces
#  files: [ dashboards/k8s-views-namespaces.json ]
#
#- name: dashboards-k8s-views-nodes
#  files: [ dashboards/k8s-views-nodes.json ]
#
#- name: dashboards-k8s-views-pods
#  files: [ dashboards/k8s-views-pods.json ]
#
#- name: dashboards-k8s-views-persistent-volumes
#  files: [ dashboards/Persistent-volumes.json ]

#################################################
# System / Addons Dashboards
#################################################

#- name: dashboards-k8s-system-api-server
#  files: [ dashboards/k8s-system-api-server.json ]
#
#- name: dashboards-k8s-system-coredns
#  files: [ dashboards/k8s-system-coredns.json ]
#
#- name: dashboards-k8s-addons-prometheus
#  files: [ dashboards/k8s-addons-prometheus.json ]

#- name: dashboards-k8s-addons-persistent-volumes
#  files: [ dashboards/Persistent-volumes.json ]

#namespace: default
#commonAnnotations:
#  app.kubernetes.io/created-by: kustomizer
#  endpointslice.kubernetes.io/managed-by: controller
#  pod-security.kubernetes.io/audit: baseline
#  pod-security.kubernetes.io/warn-version: latest



resources:
- grafana/
- loki/
- prometheus/
- promtail/
- tempo/
- app/