apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  labels:
    vol: prometheus-storage
  namespace: monitoring
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5.0Gi