apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
  labels:
    type: local
  namespace: monitoring
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dataprom"
