apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- traefik-cr.yml
- traefik-dp.yml
- traefik-svc.yml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: traefik