apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-datastore-pvc
  labels:
    vol: grafana-datastore
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5.0Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pvc
  labels:
    vol: grafana-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5.0Gi