---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app.kubernetes.io/name: grafana
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090

    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        maxLines: 1000

    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3100
      jsonData:
        httpMethod: GET
        tracesToLogs:
          datasourceUid: Loki
        tracesToLogsV2:
          datasourceUid: Loki
        tracesToMetrics:
          datasourceUid: Prometheus
        serviceMap:
          datasourceUid: Prometheus
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: Loki
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring  # Namespace correto
  labels:
    grafana_dashboard: "1"
data:
  grafana-dashboard.json: |
    {
      "id": null,
      "title": "Prometheus Metrics",
      "uid": "prometheus-dashboard",
      "timezone": "browser",
      "schemaVersion": 16,
      "version": 0,
      "refresh": "5s",
      "panels": [
        {
          "type": "graph",
          "title": "CPU Usage",
          "targets": [
            {
              "expr": "rate(node_cpu_seconds_total{mode='system'}[5m])",
              "legendFormat": "{{cpu}}"
            }
          ],
          "datasource": "Prometheus"
        }
      ]
    }
