apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  #labels:
  #  type: local
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: longhorn
  hostPath:
    path: "/datagfst"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-datastore
  #labels:
  #  type: local
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: longhorn
  hostPath:
    path: "/datagfdt"