apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana-cm.yml
- deployment.yml
- service.yml
- graf-pv.yml
- graf-pvc.yml
- secret.yml
- account.yml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: grafana