---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: rails-api
    process: web
  name: rails-api-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rails-api
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rails-api
        process: web
    spec:
      containers:
        - env:
            - name: PORT
              value: "3001"
          envFrom:
            - configMapRef:
                name: rails-api
          image: docker.io/romaofr/rails-api:latest
          imagePullPolicy: IfNotPresent
          name: rails-api-web
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /produtos
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /data
              name: grafana-storage
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage-pvc
