apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- graffback.yml
- configmap.yml
- service.yml
- graffback-ingress.yml
- secrets.yml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: graffback-api