apiVersion: v1
kind: Secret
metadata:
  name: secret_dockerhub
  namespace: monitoring # Substitua pelo seu namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-dockerconfigjson>