apiVersion: v1
kind: Service
metadata:
  name: graffback-api
  labels:
    app.kubernetes.io/name: graffback-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: NodePort
  ports:
  - name: graffback-api
    port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: graffback-api