apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kafka-ingress.yml
- kafka-namespace.yml
- kafka-network-policy.yml
- kafka-nginx-ingress.yml
- kafka-stateful-set.yml
- kafka-ui-deployment.yml
- nginx.yml
- zookeeper-stateful-set.yml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: kafka