apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-nginx
spec:
  selector:
    matchLabels:
      run: kafka-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: kafka-nginx
    spec:
      containers:
      - name: kafka-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nginx
  labels:
    run: kafka-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: kafka-nginx
---