apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yml
- namespace.yml
- promtail-clusterrole.yml
- pvc.yml
- pv.yml
- service.yml
- secret.yml
- statefulset.yml
- graffback-network-policy.yml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/name: postgres