apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graffback-api-role
  namespace: postgres
rules:
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graffback-api-rolebinding
  namespace: postgres
subjects:
- kind: ServiceAccount
  name: postgres  # Nome da conta de serviço do seu pod
roleRef:
  kind: Role
  name: graffback-api-role
  apiGroup: rbac.authorization.k8s.io