apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: postgres
type: Opaque
data:
  DB_ADDR: postgres
  DB_PORT: '5432'
  DB_DATABASE: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres