apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: postgres
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=   # base64 encoded value of 'postgres'
  postgres-password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
  postgres-db: a2V5Y2xvYWs=  # base64 encoded value of 'postgres'
  DB_DATABASE: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
