apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: postgres
type: Opaque
data:
  #postgres-user: cG9zdGdyZXM=   # base64 encoded value of 'postgres'
  #postgres-password: cG9zdGdyZXM=  # base64 encoded value of 'password'
  #postgres-db: cG9zdGdyZXM=  # base64 encoded value of 'postgres'
  DB_DATABASE: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
