#apiVersion: v1
#kind: Secret
#metadata:
#  name: postgres-db-secret
#  namespace: postgres
#type: Opaque
#data:
#  DB_ADDR: db
#  DB_PORT: '5432'
#  DB_DATABASE: postgres
#  DB_USER: postgres
#  DB_PASSWORD: postgres

apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: postgres  # Substitua pelo seu namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # 'postgres' em base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # 'postgres' em base64
  POSTGRES_DB: cG9zdGdyZXM=  # 'graffback' em base64
  #DB_DATABASE: cG9zdGdyZXM=
  #DB_USER: cG9zdGdyZXM=
  #DB_PASSWORD: cG9zdGdyZXM=